name: Build Ubuntu Touch images

on:
  push:
    branches-ignore:
      - main # Ignore main branch since it will have release tags
    tags:
      - '**'
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        device: [vndk30, vndk32, vndk33]

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Install build tools/dependencies
        run: |
          sudo apt update
          sudo apt install android-tools-mkbootimg bc bison build-essential ca-certificates cpio curl fakeroot flex git kmod libssl-dev libtinfo5 python2 sudo unzip wget xz-utils -y --no-install-recommends
          sudo ln -sf python2.7 /usr/bin/python
          sudo wget https://raw.githubusercontent.com/LineageOS/android_system_tools_mkbootimg/lineage-18.1/mkbootimg.py -O /usr/bin/mkbootimg

      - name: Build device tarball
        run: |
          ln -sf deviceinfo-${{ matrix.device }} deviceinfo
          ./build.sh
        
      - name: Upload build output
        uses: actions/upload-artifact@v3
        with:
          name: device-tarball
          path: out/*

  devel-flashable:
    needs: build
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        device: [vndk30, vndk32, vndk33]
        release: [focal, noble]

    env:
      ROOTFS_URL: ${{ matrix.release == 'focal'
        && 'https://ci.ubports.com/job/focal-hybris-rootfs-arm64/job/master/lastSuccessfulBuild/artifact/ubuntu-touch-android9plus-rootfs-arm64.tar.gz'
        || 'https://ci.ubports.com/job/focal-hybris-rootfs-arm64/job/master/lastSuccessfulBuild/artifact/ubuntu-touch-android9plus-rootfs-next-arm64.tar.gz' }}
      OTA_CHANNEL: ${{ matrix.release == 'focal'
        && '20.04/arm64/android9plus/devel'
        || 'utnext/arm64/android9plus' }}

    steps:
      - uses: actions/checkout@v3

      - name: Download device tarball
        uses: actions/download-artifact@v3
        with:
          name: device-tarball
          path: out

      - name: Install build tools/dependencies
        run: |
          sudo apt update
          sudo apt install -y fakeroot git img2simg jq sudo wget xz-utils

      - name: Clone halium-generic-adaptation-build-tools
        run: git clone https://gitlab.com/ubports/community-ports/halium-generic-adaptation-build-tools.git build

      - name: Prepare fake OTA update
        run: |
          ln -sf deviceinfo-${{ matrix.device }} deviceinfo
          DEVICE="$(source deviceinfo && echo $deviceinfo_codename)"
          ./build/prepare-fake-ota.sh out/device_${DEVICE}.tar.xz ota

      - name: Create flashable images
        run: |
          mkdir -p out
          ./build/system-image-from-ota.sh ota/ubuntu_command out
          mv out/rootfs.img out/ubuntu.img
          xz -T0 out/ubuntu.img

      - name: Upload flashable images to artifacts
        if: ${{ ! startsWith(github.ref, 'refs/tags/') }}
        continue-on-error: true
        uses: actions/upload-artifact@v3
        with:
          name: images-${{ matrix.device }}-${{ matrix.release }}
          path: |
            out/boot.img
            out/ubuntu.img.xz

      - name: Release flashable images
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
        run: |
            mv out/ubuntu.img.xz ${{ matrix.device }}-ubuntu.img.xz
            gh release create ${{ github.ref_name }} *-ubuntu.img.xz || \
                gh release upload ${{ github.ref_name }} *-ubuntu.img.xz --clobber
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
